@module("../assets/logo.svg") external logo: string = "default"
@module("../assets/empty-state.svg") external emptyState: string = "default"
@module("../assets/spinner.svg") external spinner: string = "default"
@module("../assets/trash-icon.svg") external trashIcon: string = "default"
@module("../assets/check-icon.svg") external checkIcon: string = "default"
@module("../assets/x-icon.svg") external xIcon: string = "default"
